/*
 * my-swagger
 *
 * This is my first sample for Swagger (Open-API)
 *
 * API version: 1.0.0
 * Contact: example@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TestPost struct for TestPost
type TestPost struct {
	Name string `json:"name"`
	Tag string `json:"tag,omitempty"`
}
